# Generated by Django 5.2.12 on 2026-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64, verbose_name='الباركود')),
                ('item_code', models.CharField(db_index=True, max_length=64, verbose_name='رقم الصنف')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الصنف')),
                ('unit', models.CharField(blank=True, default='', max_length=64, verbose_name='الوحدة')),
                ('pack_size', models.CharField(blank=True, default='', max_length=32, verbose_name='حجم العبوة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'باركود صنف',
                'verbose_name_plural': 'باركودات الأصناف',
                'constraints': [models.UniqueConstraint(fields=('barcode', 'item_code', 'unit'), name='uniq_barcode_item_unit')],
            },
        ),
    ]
