# Generated by Django 5.2.12 on 2026-07-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_code', models.CharField(max_length=64, unique=True, verbose_name='رمز المجموعة')),
                ('g_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم المجموعة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مجموعة صنف',
                'verbose_name_plural': 'مجموعات الأصناف',
            },
        ),
        migrations.AddField(
            model_name='itembarcode',
            name='g_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='رمز المجموعة'),
        ),
    ]
