# Generated by Django 5.2.12 on 2026-07-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembarcode',
            name='barcode',
            field=models.CharField(db_index=True, max_length=128, verbose_name='الباركود'),
        ),
    ]
