# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_itembarcode_uniq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStockValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(db_index=True, max_length=16, verbose_name='المخزن')),
                ('item_code', models.CharField(db_index=True, max_length=64, verbose_name='رقم الصنف')),
                ('g_code', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='رمز المجموعة')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='إجمالي التكلفة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رصيد تكلفة صنف',
                'verbose_name_plural': 'أرصدة تكلفة الأصناف',
            },
        ),
        migrations.AddConstraint(
            model_name='itemstockvalue',
            constraint=models.UniqueConstraint(fields=('warehouse', 'item_code'), name='uniq_warehouse_item_stock'),
        ),
        migrations.AddIndex(
            model_name='itemstockvalue',
            index=models.Index(fields=['warehouse', 'g_code'], name='idx_stock_wh_group'),
        ),
    ]
