# Generated by Django 5.2.12 on 2026-09-02 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_useractivitysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNavPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(blank=True, default=list, verbose_name='الأقسام الممنوحة')),
                ('blocked_screens', models.JSONField(blank=True, default=list, verbose_name='الشاشات المحجوبة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nav_permission', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية أقسام',
                'verbose_name_plural': 'صلاحيات الأقسام',
            },
        ),
    ]
