# Generated by Django 5.2.12 on 2026-10-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_usernavpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_host', models.CharField(blank=True, default='', max_length=200, verbose_name='خادم أوراكل')),
                ('oracle_port', models.PositiveIntegerField(default=1521, verbose_name='المنفذ')),
                ('oracle_service_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Service Name')),
                ('oracle_user', models.CharField(blank=True, default='', max_length=100, verbose_name='مستخدم أوراكل')),
                ('oracle_password_enc', models.TextField(blank=True, default='', verbose_name='كلمة السر (مشفّرة)')),
                ('oracle_schema', models.CharField(blank=True, default='', max_length=60, verbose_name='المخطط (Schema)')),
                ('default_warehouse', models.CharField(blank=True, default='', max_length=20, verbose_name='المخزن الافتراضي')),
                ('compare_warehouses', models.CharField(blank=True, default='', max_length=300, verbose_name='مخازن المقارنة')),
                ('warehouses_text', models.TextField(blank=True, default='', verbose_name='قائمة المخازن (كود=اسم)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الربط',
                'verbose_name_plural': 'إعدادات الربط',
            },
        ),
    ]
